import torch as t


AUDITION_LOSS_WEIGHTS = t.tensor([0.0166, 0.0575, 0.0977, 0.0636, 0.0240, 0.0419, 0.0440, 0.1225])

# 0 = "music"
# 1 = "animals"
# 2 = "speech"
# 3 = "outdoor environment"
# 4 = "indoor environment"
# 5 = "machine"
# 6 = "human sounds"
# 7 = "nature"

AUDITION_RELABEL = {
    "Accordion": 0,
    "Acoustic_guitar": 0,
    "Bass_drum": 0,
    "Bass_guitar": 0,
    "Bowed_string_instrument": 0,
    "Brass_instrument": 0,
    "Crash_cymbal": 0,
    "Wind_instrument_and_woodwind_instrument": 0,
    "Cymbal": 0,
    "Glockenspiel": 0,
    "Drum": 0,
    "Drum_kit": 0,
    "Trumpet": 0,
    "Guitar": 0,
    "Electric_guitar": 0,
    "Singing": 0,
    "Keyboard_(musical)": 0,
    "Harmonica": 0,
    "Hi-hat": 0,
    "Male_singing": 0,
    "Tabla": 0,
    "Tambourine": 0,
    "Music": 0,
    "Musical_instrument": 0,
    "Mallet_percussion": 0,
    "Marimba_and_xylophone": 0,
    "Female_singing": 0,
    "Snare_drum": 0,
    "Percussion": 0,
    "Piano": 0,
    "Plucked_string_instrument": 0,
    "Rattle_(instrument)": 0,
    "Organ": 0,
    "Scratching_(performance_technique)": 0,
    "Strum": 0,
    "Harp": 0,
    "Cowbell": 0,

    "Animal": 1,
    "Bark": 1,
    "Bird": 1,
    "Bird_vocalization_and_bird_call_and_bird_song": 1,
    "Cat": 1,
    "Cricket": 1,
    "Crow": 1,
    "Meow": 1,
    "Chirp_and_tweet": 1,
    "Dog": 1,
    "Wild_animals": 1,
    "Fowl": 1,
    "Frog": 1,
    "Purr": 1,
    "Livestock_and_farm_animals_and_working_animals": 1,
    "Chicken_and_rooster": 1,
    "Domestic_animals_and_pets": 1,
    "Growling": 1,
    "Gull_and_seagull": 1,
    "Hiss": 1,
    "Insect": 1,

    "Child_speech_and_kid_speaking": 2,
    "Female_speech_and_woman_speaking": 2,
    "Male_speech_and_man_speaking": 2,
    "Speech": 2,
    "Speech_synthesizer": 2,
    "Whispering": 2,
    "Yell": 2,
    "Human_voice": 2,
    "Conversation": 2,

    "Bell": 3,
    "Bicycle_bell": 3,
    "Crowd": 3,
    "Boom": 3,
    "Buzz": 3,
    "Car_passing_by": 3,
    "Chime": 3,
    "Church_bell": 3,
    "Crushing": 3,
    "Explosion": 3,
    "Fire": 3,
    "Fireworks": 3,
    "Glass": 3,
    "Gong": 3,
    "Idling": 3,
    "Ratchet_and_pawl": 3,
    "Rattle": 3,
    "Ringtone": 3,
    "Run": 3,
    "Screech": 3,
    "Shatter": 3,
    "Siren": 3,
    "Skateboard": 3,
    "Slam": 3,
    "Thump_and_thud": 3,

    "Alarm": 4,
    "Bathtub_(filling_or_washing)": 4,
    "Boiling": 4,
    "Chink_and_clink": 4,
    "Clock": 4,
    "Coin_(dropping)": 4,
    "Computer_keyboard": 4,
    "Crumpling_and_crinkling": 4,
    "Cupboard_open_or_close": 4,
    "Cutlery_and_silverware": 4,
    "Dishes_and_pots_and_pans": 4,
    "Domestic_sounds_and_home_sounds": 4,
    "Door": 4,
    "Doorbell": 4,
    "Drawer_open_or_close": 4,
    "Knock": 4,
    "Liquid": 4,
    "Keys_jangling": 4,
    "Packing_tape_and_duct_tape": 4,
    "Printer": 4,
    "Scissors": 4,
    "Sink_(filling_or_washing)": 4,
    "Sliding_door": 4,
    "Splash_and_splatter": 4,
    "Squeak": 4,
    "Tap": 4,
    "Tearing": 4,
    "Telephone": 4,
    "Toilet_flush": 4,
    "Typewriter": 4,
    "Typing": 4,
    "Water_tap_and_faucet": 4,
    "Writing": 4,
    "Zipper_(clothing)": 4,
    "Tick": 4,
    "Tick-tock": 4,
    "Microwave_oven": 4,
    "Crack": 4,
    "Crackle": 4,
    "Drip": 4,
    "Fill_(with_liquid)": 4,
    "Frying_(food)": 4,

    "Accelerating_and_revving_and_vroom": 5,
    "Aircraft": 5,
    "Bicycle": 5,
    "Boat_and_Water_vehicle": 5,
    "Bus": 5,
    "Camera": 5,
    "Car": 5,
    "Drill": 5,
    "Engine": 5,
    "Engine_starting": 5,
    "Fixed-wing_aircraft_and_airplane": 5,
    "Gunshot_and_gunfire": 5,
    "Mechanical_fan": 5,
    "Mechanisms": 5,
    "Motor_vehicle_(road)": 5,
    "Power_tool": 5,
    "Race_car_and_auto_racing": 5,
    "Rail_transport": 5,
    "Subway_and_metro_and_underground": 5,
    "Traffic_noise_and_roadway_noise": 5,
    "Train": 5,
    "Truck": 5,
    "Vehicle": 5,
    "Vehicle_horn_and_car_horn_and_honking": 5,
    "Whoosh_and_swoosh_and_swish": 5,
    "Hammer": 5,
    "Motorcycle": 5,
    "Tools": 5,
    "Sawing": 5,

    "Cheering": 6,
    "Applause": 6,
    "Burping_and_eructation": 6,
    "Chatter": 6,
    "Cough": 6,
    "Breathing": 6,
    "Chuckle_and_chortle": 6,
    "Chewing_and_mastication": 6,
    "Clapping": 6,
    "Fart": 6,
    "Finger_snapping": 6,
    "Respiratory_sounds": 6,
    "Crying_and_sobbing": 6,
    "Gasp": 6,
    "Giggle": 6,
    "Gurgling": 6,
    "Hands": 6,
    "Human_group_actions": 6,
    "Laughter": 6,
    "Screaming": 6,
    "Shout": 6,
    "Sigh": 6,
    "Sneeze": 6,
    "Walk_and_footsteps": 6,

    "Ocean": 7,
    "Pour": 7,
    "Rain": 7,
    "Raindrop": 7,
    "Stream": 7,
    "Thunder": 7,
    "Thunderstorm": 7,
    "Water": 7,
    "Waves_and_surf": 7,
    "Wind": 7,
    "Wind_chime": 7,
    "Wood": 7,
    "Trickle_and_dribble": 7,
}
